### ISSUE TITLE
user story 20 - Update `Tasks` Schema to include `date_created` and `date_updated`

### ISSUE THREAD

**Issue by MarchandMD** [dnvr-zero/dnvr-zero-be#41]
FE is asking for `date_created` or `created_on` to enable sorting

Original site has additional options for sorting tasks

![Image](https://user-images.githubusercontent.com/35391349/248075090-263579e8-edad-45c9-87d3-66b2e6f1e9ae.png)

- Would need to update TaskSchema (src/models/Tasks.js)
- Would need to add a default value
- Would easily be a String
- How could we use JS to create a default Date value? 
- Would need to update the Swagger documentation (probably in `app.js`?)

**Comment by msakr21** [comment]
Not sure yet how to tackle it, but I'd be happy to give it a shot!

**Comment by MarchandMD** [comment]
I'm happy to pair on this one! @msakr21 just shoot me a slack message

**Comment by MarchandMD** [comment]
done
